apiVersion: v1
kind: Namespace
metadata:
  name: prod

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prod
spec:
  selector:
    app: prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prod
spec:
  serviceName: prometheus
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeSelector:
        node-group: eks-prometheus
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:v2.36.1
          ports:
            - containerPort: 9090
          command:
            - '--storage.tsdb.retention.time=5m'
          volumeMounts:
            - name: prometheus-data
              mountPath: /prometheus/data
            - name: prometheus-config
              mountPath: /prometheus/prometheus.yml
              subPath: prometheus.yml
  volumeClaimTemplates:
    - metadata:
        name: prometheus-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi  # Adjust size as needed
        storageClassName: gp2-csi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prod
data:
  prometheus.yml: |
    global:
      scrape_interval: '15s'
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
