apiVersion: v1
kind: Namespace
metadata:
  name: prod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: redis-data
              mountPath: /data
          args: ["--save", "60", "1", "--appendonly", "yes"]  # Optional: Redis persistence config
      restartPolicy: Always
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-redis
      volumes:
        - name: redis-data
          emptyDir: {}  # Temporary storage, replace with a PVC if needed

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: prod
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
