# Vagrantfile to create three Ubuntu machines with static IPs and install required packages
Vagrant.configure("2") do |config|
  
  # Specify the base box
  config.vm.box = "ubuntu/bionic64" # Replace with your preferred Ubuntu box
  
  # Set up the first machine - docker-master
  config.vm.define "docker-master" do |master|
    master.vm.hostname = "docker-master"
    master.vm.network "public_network", ip: "192.168.1.100", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "docker-master"
      vb.memory = "1024"
      vb.cpus = 1
    end
    # Provisioning script to install docker.io, net-tools, vim, and iftop
    master.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y docker.io net-tools vim iftop
      sudo systemctl enable docker
      sudo systemctl start docker
    SHELL
  end

  # Set up the second machine - docker-worker
  config.vm.define "docker-worker" do |worker|
    worker.vm.hostname = "docker-worker"
    worker.vm.network "public_network", ip: "192.168.1.101", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "docker-worker"
      vb.memory = "1024"
      vb.cpus = 1
    end
    # Provisioning script to install docker.io, net-tools, vim, and iftop
    worker.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y docker.io net-tools vim iftop
      sudo systemctl enable docker
      sudo systemctl start docker
    SHELL
  end

  # Set up the third machine - docker-worker-2
  config.vm.define "docker-worker-2" do |worker2|
    worker2.vm.hostname = "docker-worker-2"
    worker2.vm.network "public_network", ip: "192.168.1.102", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz"
    worker2.vm.provider "virtualbox" do |vb|
      vb.name = "docker-worker-2"
      vb.memory = "1024"
      vb.cpus = 1
    end
    # Provisioning script to install docker.io, net-tools, vim, and iftop
    worker2.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y docker.io net-tools vim iftop
      sudo systemctl enable docker
      sudo systemctl start docker
    SHELL
  end
end
