apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: vernemq
    meta.helm.sh/release-namespace: prod
  labels:
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/name: vernemq
  name: vernemq
  namespace: prod
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
  - name: mqtts
    port: 8883
    protocol: TCP
    targetPort: mqtts
  - name: mqtt-ditto
    port: 1880
    protocol: TCP
    targetPort: 1880
  - name: iotrelay
    port: 8884
    protocol: TCP
    targetPort: 8884
  selector:
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/name: vernemq
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-namespace: prod
  labels:
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/name: vernemq
  name: vernemq-headless
  namespace: prod
spec:
  clusterIP: None
  ports:
  - name: empd
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: metrics
    port: 8888
    protocol: TCP
    targetPort: prometheus
  selector:
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/name: vernemq
  sessionAffinity: None
  type: ClusterIP
