apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: vernemq
    app.kubernetes.io/name: vernemq
  name: vernemq
  namespace: prod
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: vernemq
      app.kubernetes.io/name: vernemq
  serviceName: vernemq-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: vernemq
        app.kubernetes.io/name: vernemq
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - vernemq
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: MY_POD_NAME
          valueFrom:
             fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: DOCKER_VERNEMQ_DISCOVERY_KUBERNETES
          value: "1"
        - name: DOCKER_VERNEMQ_KUBERNETES_LABEL_SELECTOR
          value: app.kubernetes.io/name=vernemq,app.kubernetes.io/instance=vernemq
        - name: DOCKER_VERNEMQ_LISTENER__TCP__LOCALHOST
          value: 127.0.0.1:1883
        - name: DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT
          value: 0.0.0.0:8883
        - name: DOCKER_VERNEMQ_LISTENER__SSL__IOTRELAY
          value: 0.0.0.0:8884
        - name: DOCKER_VERNEMQ_LISTENER__TCP__DITTO
          value: 0.0.0.0:1880
        - name: DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT
          value: "on"
        - name: DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT
          value: "on"
        - name: DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT
          value: "on"
        - name: DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT
          value: "on"
        - name: DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL
          value: "debug"
        - name: DOCKER_VERNEMQ_ACCEPT_EULA
          value: "yes"
        - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
          value: "on"
        - name: DOCKER_VERNEMQ_PLUGINS__VMQ_ACL
          value: "on"
        - name: DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD
          value: "off"
        - name: DOCKER_VERNEMQ_LISTENER__SSL__USE_IDENTITY_AS_USERNAME
          value: "on"
        - name: DOCKER_VERNEMQ_LISTENER__SSL__REQUIRE_CERTIFICATE
          value: "on"
        - name: DOCKER_VERNEMQ_PLUGINS__VMQ_GENERIC_MSG_STORE
          value: "off"
        - name: DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES
          value: "-1"
        - name: DOCKER_VERNEMQ_MAX_OFFLINE_MESSAGES
          value: "-1"
        image: vernemq/vernemq:1.12.3-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: prometheus
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: vernemq
        ports:
        - containerPort: 8884
          name: iotrelay
          protocol: TCP
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        - containerPort: 1880
          name: mqtt-ditto
          protocol: TCP
        - containerPort: 8883
          name: mqtts
          protocol: TCP
        - containerPort: 4369
          name: epmd
          protocol: TCP
        - containerPort: 44053
          name: vmq
          protocol: TCP
        - containerPort: 8080
          name: ws
          protocol: TCP
        - containerPort: 8443
          name: wss
          protocol: TCP
        - containerPort: 8888
          name: prometheus
          protocol: TCP
        - containerPort: 9100
          protocol: TCP
        - containerPort: 9101
          protocol: TCP
        - containerPort: 9102
          protocol: TCP
        - containerPort: 9103
          protocol: TCP
        - containerPort: 9104
          protocol: TCP
        - containerPort: 9105
          protocol: TCP
        - containerPort: 9106
          protocol: TCP
        - containerPort: 9107
          protocol: TCP
        - containerPort: 9108
          protocol: TCP
        - containerPort: 9109
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: prometheus
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /vernemq/log
          name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10000
        runAsGroup: 10000
        runAsUser: 10000
      serviceAccount: vernemq
      serviceAccountName: vernemq
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: logs
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-verne-mq
  updateStrategy:
    type: RollingUpdate