Vagrant.configure("2") do |config|
  # Define the first VM
  config.vm.define "machine1" do |machine1|
    machine1.vm.box = "bento/ubuntu-24.04"
    machine1.vm.network "public_network", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz", use_dhcp: true
    machine1.vm.synced_folder "./shared", "/vagrant_shared"
    machine1.vm.boot_timeout = 180
    
    machine1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y mysql-server
      sudo systemctl enable mysql
      sudo systemctl start mysql
    SHELL
  end
  
  # Define the second VM
  config.vm.define "machine2" do |machine2|
    machine2.vm.box = "bento/ubuntu-24.04"
    machine2.vm.network "public_network", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz", use_dhcp: true
    machine2.vm.synced_folder "./shared", "/vagrant_shared"
    machine2.vm.boot_timeout = 180
    
    machine2.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y mysql-server
      sudo systemctl enable mysql
      sudo systemctl start mysql
    SHELL
  end
end
