apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: groupadmin
  namespace: prod
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: Delete
        host: "*"
