Vagrant.configure("2") do |config|

  (1..3).each do |i|
    config.vm.define "webserver#{i}" do |webserver|
      webserver.vm.box = "bento/ubuntu-24.04"
      webserver.vm.network "public_network", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz", use_dhcp: true
      webserver.vm.synced_folder "./shared", "/vagrant_shared"
      webserver.vm.boot_timeout = 600
      webserver.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y nginx
      SHELL
    end
  end


  config.vm.define "private_server" do |private_server|
    private_server.vm.box = "bento/ubuntu-24.04"
    private_server.vm.network "private_network", ip: "192.168.50.4"
    private_server.vm.synced_folder "./shared1", "/vagrant_shared1"
    private_server.vm.boot_timeout = 600
    private_server.vm.provision "shell", path: "scripts/provision.sh"
  end

  config.vm.define "public_server" do |public_server|
    public_server.vm.box = "bento/ubuntu-24.04"
    public_server.vm.network "public_network", ip: "192.168.1.100", bridge: "Intel(R) Wi-Fi 6 AX201 160MHz"
    public_server.vm.synced_folder "./shared2", "/vagrant_shared2"
    public_server.vm.boot_timeout = 600
    public_server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nginx
    SHELL
  end

end
